### ISSUE TITLE
Discrete delays have slightly larger log standard deviation than continuous delays

### ISSUE THREAD

**Issue by parksw3** [parksw3/epidist-paper#16]
See `scripts/test_discrete.R`

* Simulated 1000 delays assuming for growth rates ranging between -0.2 and 0.2. Repeated 20 times per growth rate.
* Directly calculated logsd for continuous and discrete delays

![test_discrete](https://user-images.githubusercontent.com/18031050/199147998-be708903-32bb-4464-b320-b6390c664792.png)

* discrete sdlog is always (?) bigger than continuous sdlog, but the relative ratios are generally small (~2%)
* It's possible that the opposite is true for other distributions? We obviously can't test all possible parameter/distribution combinations but good to know this for understanding fitting results.

**Comment by parksw3** [comment]
![test_discrete2](https://user-images.githubusercontent.com/18031050/199148228-e671075b-747a-4683-abc8-0da2e0db497d.png)

Results for meanlog. But not big enough to worry about. 

Something about cases being closer to the either edge depending on the growth rate?

**Comment by seabbs** [comment]
I think this will be covered in the simulation grid we are planning to include so marking this as for discussion in the paper.

**Comment by seabbs** [comment]
I think we have covered this (well you have) in the new censoring plot and discussion so closing here.
