### ISSUE TITLE
Time-varying delays

### ISSUE THREAD

**Issue by seabbs** [parksw3/epidist-paper#33]
We in theory have the capacity to estimate time-varying delays and discussed doing so as part of our case study (#9). However, as @parksw3 points out below we can really only approximate this as well can't specify based on the true primary event time but instead only the censored lower (or upper bounds). As also mentioned in the daily case this is likely a good enough approximation but in case with longer censoring window the approximation likely breaks down. 

We should add a discussion of this (and the further work needed (i.e evaluation?)) to the discussion.

From @parksw3 

https://github.com/parksw3/dynamicaltruncation/issues/9#issuecomment-131403109

**Comment by parksw3** [comment]
And since we are dealing with daily delays, it's probably not a bad idea to try the time-varying delay and then explain why it's not necessarily a good idea (instead of not doing and saying it's bad).

**Comment by seabbs** [comment]
Noting we now have a moving window analysis (for the case study) but still need to mention having a time-varying model solution in the discussion.

**Comment by parksw3** [comment]
I agree. I think I say it in the paper briefly. But will try to make this clearer, especially in the methods section.
