### ISSUE TITLE
Change figure 4

### ISSUE THREAD

**Issue by parksw3** [parksw3/epidist-paper#38]
- Divide into two figures
- The first figure is empirical (traj, time-varying mean, multi panel, amount of truncation)
- The second figure is fits

**Comment by parksw3** [comment]
I got stuck trying to come up with a better way of doing the dynamical correction with lognormal (currently using Poisson, which is not ideal) so decided to work on making figures. 

![case_study1](https://user-images.githubusercontent.com/18031050/219577294-42023c55-2f8b-43f5-a9a8-7346bf19c671.png)

This is a new potential figure 4. Now panel B shows 3 different means. The forward mean, which is what we want to understand (but not in this paper). And cumulative real-time and retrospective means, which are going to correspond to what we estimate with our naive methods.

I couldn't figure out how to get rid of the guide for panel C in the combined figure but maybe you know how to do that?

**Comment by seabbs** [comment]
Ah lovely! You were right these are great additions. I

**Comment by seabbs** [comment]
I had a quick parse to clean up the legends and generally had a fiddle. 

![case_study1](https://user-images.githubusercontent.com/20317649/219664349-9566163f-c350-4204-b359-9e6aa39dbc6b.png)

**Comment by seabbs** [comment]
I just looked at adding posterior predictions to the results graph (see below). Its not incredibly useful because we are fitting to the full sample vs a windowed sample. Given that the mean varies over time etc perhaps this is giving us a hint it would be. nice to fit to an observation window (i.e 30 days back from the observation time) to better reflect the approach you might take with a data set of this kind? 

It would mean potentially needing to rework some of these figures and the associated text (basically moving from cumulative to windowed).

**Comment by parksw3** [comment]
Ah yes, I agree that the posterior predictive plot isn't so useful when the mean is changing. The fits at t=240 look pretty bad (as it should be). 

> be. nice to fit to an observation window (i.e 30 days back from the observation time) to better reflect the approach you might take with a data set of this kind?

This is a good idea. Not sure if it's the kind of approach that one might take with a data set of this kind though---I guess this varies between people. If I was analyzing this data during an actual outbreak, I might just look at the empirical mean vs sd and call it a day...but obviously that's not what people want (and that's why we're doing this)... Anyway, I think fitting to observation windows makes more sense.

**Comment by seabbs** [comment]
> This is a good idea. Not sure if it's the kind of approach that one might take with a data set of this kind though---I guess this varies between people. If I was analyzing this data during an actual outbreak, I might just look at the empirical mean vs sd and call it a day...but obviously that's not what people want (and that's why we're doing this)... Anyway, I think fitting to observation windows makes more sense.

So this rolling window approach would be exactly what I would do/have done if I wanted the distribution in an outbreak for some other use case  and given available methods + not being able to fit it directly as time-varying.

I've just run this (with a window of 60 days). It looks as I would expect basically. Something this highlighted to me is how close the mean estimates actually are to each other for this case study which I guess is a good thing given that all the papers looking at this use a range of the worst offending models. There is a PR with the update here (#44). I don't mind if we stick with what we currently have or go with this but if we do update then unfortunately some work is needed on the empirical case study plot to bring it into line. 
![case_study2](https://user-images.githubusercontent.com/20317649/219778074-27f74782-4c44-46a9-8066-d4174f6d86aa.png)

**Comment by parksw3** [comment]
Sorry, not sure how I missed this.

Yes, this looks much better. I can work on updating the empirical plots. I think we can drop the cumulative means and just focus on the forward mean for the empirical plot.

**Comment by seabbs** [comment]
I like the updated empirical plot but I wonder if we should plot the rolling % of secondary observations observed from the last 60 day window (to make it comparable across time) and also if we should plot the forward as well as the backwards mean (this might be nice to highlight they are different and how that works).

**Comment by parksw3** [comment]
> I wonder if we should plot the rolling % of secondary observations observed from the last 60 day window

Not sure what you mean here...  

> also if we should plot the forward as well as the backwards mean (this might be nice to highlight they are different and how that works).

This is a good point. Will try this when I get home. Currently at school with my mac which is pretty broken and can't run things in this package...

**Comment by seabbs** [comment]
> This is a good point. Will try this when I get home. Currently at school with my mac which is pretty broken and can't run things in this package...

I feel like this issue needs to be in the acknowledgements of this paper.

> Not sure what you mean here...

I'll have a go prototyping what I mean (essentially rather than having it be cohort based as it is now have a rolling window so that it is always what would be the % of secondary observations truncated if we observed at any given t).

**Comment by seabbs** [comment]
Done on this I think
