### ISSUE TITLE
Resolve TODOs and FIXMEs.

### ISSUE THREAD

**Issue by seabbs** [parksw3/epidist-paper#40]
I see the attached TODOs and FIXMEs floating around the code base. We should look at resolving these ASAP in particular the FIXMEs as some of these could indicatee issues. I think most of these have been resolved but I could also be mistaken.
![Screenshot 2023-02-16 at 18 43 59](https://user-images.githubusercontent.com/20317649/219458866-d35b2e67-12c1-4e28-affb-f5bed3db8a5b.png)

**Comment by parksw3** [comment]
FIXME is the Ebola problem, which we fixed in https://github.com/parksw3/epidist-paper/issues/29.

**Comment by seabbs** [comment]
Down to these now which are just choices to make for SI plots.

![Screenshot 2023-02-17 at 11 14 34](https://user-images.githubusercontent.com/20317649/219635190-c2955097-ad5b-40db-808f-caff52117304.png)

**Comment by seabbs** [comment]
These are all good I think now apart from ones we may want to add to the SI at a later date (as noted above).
